name: mirror-repo-merge
on: 
  pull_request:
    types: [closed]
jobs: 
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v1
      - name: mirror-repository
        uses: spyoungtech/mirror-action@v0.4.0
        with:
            REMOTE: ${GITHUB_REPOSITORY}"
            GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
            GIT_SSH_NO_VERIFY_HOST: "true"
            DEBUG: "true"
