name: mirror-repo
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: mirror-repository
        uses: spyoungtech/mirror-action@v0.4.0
        with:
            REMOTE: ${{ secrets.REMOTE }} 
            GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
            GIT_SSH_NO_VERIFY_HOST: "true"
            DEBUG: "true"
