name: mirror-repo on PUSH
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: mirror-repository
        uses: nhsllc/mirror-action@v0.4.0
        with:
            REMOTE: ${GITHUB_REPOSITORY} 
            GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
            GIT_SSH_NO_VERIFY_HOST: "true"
            DEBUG: "true
