name: mirror-repo
on: 
  push:
    branches:
    - '**'
  pull_request:
    types: [closed]
    branches:
    - '**'
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: mirror-repository
        uses: spyoungtech/mirror-action@v0.4.3
        with:
            GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
            GIT_SSH_NO_VERIFY_HOST: "true"
            REMOTE: ${{ secrets.GITLAB_REMOTE_ORG_PATH }}${{ github.event.repository.name }}.git
            DEBUG: "true"
